### ISSUE TITLE
Enforcing cfg/kernelcraft.conf to be installed into /etc

### ISSUE THREAD

**Issue by marcosps** [arighi/kernelcraft#3]
Looking at kernelcraft/run.py, it first checks if there is a .kernelcraft.conf at the user $HOME. In this case, shouldn't be easier if the requirement of creating a file under /etc be relaxed and default it to the user home in the first place?

Thanks!

**Comment by arighi** [comment]
@marcosps I agree, thanks for the suggestion, I'll make this change.
